hide_download: true
hide_download_original: null
leftnav:
- identifier: 9b58679b-9c6a-4b17-5ef8-79815817bf18
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: fe071558-a240-cff9-bbbc-ca80683ac7d2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9a19909c-3e81-3719-371e-073643365598
  name: Instructor Insights
  pageRef: /pages/instructor-insights/
  weight: 30
- identifier: aecac14d-3981-02c1-3364-a354c44c2a8d
  name: Reading the City
  pageRef: /pages/instructor-insights/reading-the-city
  parent: 9a19909c-3e81-3719-371e-073643365598
  weight: 40
- identifier: 79681dbc-2d6a-6f6a-ad52-967561f132f7
  name: Structuring a Communication-Intensive Course
  pageRef: /pages/instructor-insights/structuring-a-communication-intensive-course
  parent: 9a19909c-3e81-3719-371e-073643365598
  weight: 50
- identifier: 9f88e4ee-f73d-6ef4-f59b-c45fa9badc7d
  name: Leading Productive Field Trips
  pageRef: /pages/instructor-insights/leading-productive-field-trips
  parent: 9a19909c-3e81-3719-371e-073643365598
  weight: 60
- identifier: ba42cb06-6687-5e06-c497-ddb8645fc880
  name: Flipping the Classroom
  pageRef: /pages/instructor-insights/flipping-the-classroom
  parent: 9a19909c-3e81-3719-371e-073643365598
  weight: 70
- identifier: b66ecc11-de23-3c45-4035-bcd3ca798874
  name: Drawing Inspiration from Research
  pageRef: /pages/instructor-insights/drawing-inspiration-from-research
  parent: 9a19909c-3e81-3719-371e-073643365598
  weight: 80
- identifier: fad67e91-4d95-0355-dde9-3f0776b43ed1
  name: Readings
  pageRef: /pages/readings
  weight: 90
- identifier: 2b653594-7e36-695e-77f0-817e67553db4
  name: Assignments
  pageRef: /pages/assignments/
  weight: 100
- identifier: bf2053d9-013c-9b07-eb2c-da426f3f66da
  name: 'Assignment Guide: Journals'
  pageRef: /pages/assignments/assignment-guide-journals
  parent: 2b653594-7e36-695e-77f0-817e67553db4
  weight: 110
- identifier: f1403dd2-7f4d-6cf8-923d-478a894b6205
  name: 'Assignment 1: Select A Site'
  pageRef: /pages/assignments/assignment-1-select-a-site
  parent: 2b653594-7e36-695e-77f0-817e67553db4
  weight: 120
- identifier: bf39994b-1e14-9bcb-34d1-e88a771e27fe
  name: 'Assignment 2: Your Site and Natural Processes'
  pageRef: /pages/assignments/assignment-2-your-site-and-natural-processes
  parent: 2b653594-7e36-695e-77f0-817e67553db4
  weight: 130
- identifier: 94eadc85-e005-7537-1175-45842aaf061b
  name: 'Assignment 3: Your Site Over Time'
  pageRef: /pages/assignments/assignment-3-your-site-over-time
  parent: 2b653594-7e36-695e-77f0-817e67553db4
  weight: 140
- identifier: 11be16ff-59a9-9a87-5ac8-7525eacd82ec
  name: 'Assignment 4: Artifacts, Layers, Traces, and Trends'
  pageRef: /pages/assignments/assignment-4-artifacts-layers-traces-and-trends
  parent: 2b653594-7e36-695e-77f0-817e67553db4
  weight: 150
- identifier: 3a8691a5-b5f7-ff36-3b59-142154604677
  name: Projects
  pageRef: /pages/projects
  weight: 160
